// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function scr_set_starting_array(my_index){
	
	
	
	start_bullet_x[primary_actions.idle]="Idle"
	start_bullet_x[primary_actions.idle_up]="Idle up"
	start_bullet_x[primary_actions.idle_down]="Idle down"
	start_bullet_x[primary_actions.idle_diagonal_up]="Diag up"
	start_bullet_x[primary_actions.idle_diagonal_down]="Diag down"
	start_bullet_x[primary_actions.run]="Run"
	start_bullet_x[primary_actions.run_up]="Run up"
	start_bullet_x[primary_actions.run_down]="Run down"
	start_bullet_x[primary_actions.duck]="Duck"
	start_bullet_x[primary_actions.jump]="Jump"
	start_bullet_x[primary_actions.fall]="Fall"
	start_bullet_x[primary_actions.dropped]="Dropped"
	start_bullet_x[primary_actions.twohand]="Twohand stance"
	start_bullet_x[primary_actions.wallcling]="Wallcling"
	start_bullet_x[primary_actions.wallmove]="Wallmove"
	start_bullet_x[primary_actions.wallcling_up]="Wallcling up"
	start_bullet_x[primary_actions.wallcling_down]="Wallcling down"
	start_bullet_x[primary_actions.wallcling_up_diagonal]="Wallcling diagonal up"
	start_bullet_x[primary_actions.wallcling_down_diagonal]="Wallcling diagonal down"
	start_bullet_x[primary_actions.ceiling]="ceiling"
	start_bullet_x[primary_actions.ceiling_move]="ceiling_move"
	start_bullet_x[primary_actions.ceiling_up]="ceiling up"
	start_bullet_x[primary_actions.ceiling_down]="ceiling down"
	start_bullet_x[primary_actions.ceiling_diagonal_up]="ceiling diagonal up"
	start_bullet_x[primary_actions.ceiling_diagonal_down]="ceiling diagonal down"
	
	start_bullet_y[primary_actions.idle]="Idle"
	start_bullet_y[primary_actions.idle_up]="Idle up"
	start_bullet_y[primary_actions.idle_down]="Idle down"
	start_bullet_y[primary_actions.idle_diagonal_up]="Diag up"
	start_bullet_y[primary_actions.idle_diagonal_down]="Diag down"
	start_bullet_y[primary_actions.run]="Run"
	start_bullet_y[primary_actions.run_up]="Run up"
	start_bullet_y[primary_actions.run_down]="Run down"
	start_bullet_y[primary_actions.duck]="Duck"
	start_bullet_y[primary_actions.jump]="Jump"
	start_bullet_y[primary_actions.fall]="Fall"
	start_bullet_y[primary_actions.dropped]="Dropped"
	start_bullet_y[primary_actions.twohand]="Twohand stance"
	start_bullet_y[primary_actions.wallcling]="Wallcling"
	start_bullet_y[primary_actions.wallmove]="Wallmove"
	start_bullet_y[primary_actions.wallcling_up]="Wallcling up"
	start_bullet_y[primary_actions.wallcling_down]="Wallcling down"
	start_bullet_y[primary_actions.wallcling_up_diagonal]="Wallcling diagonal up"
	start_bullet_y[primary_actions.wallcling_down_diagonal]="Wallcling diagonal down"
	start_bullet_y[primary_actions.ceiling]="ceiling"
	start_bullet_y[primary_actions.ceiling_move]="ceiling_move"
	start_bullet_y[primary_actions.ceiling_up]="ceiling up"
	start_bullet_y[primary_actions.ceiling_down]="ceiling down"
	start_bullet_y[primary_actions.ceiling_diagonal_up]="ceiling diagonal up"
	start_bullet_y[primary_actions.ceiling_diagonal_down]="ceiling diagonal down"
	
	
}